config/routes.rb
Rails.application.routes.draw do
  # For details on thRails.application.routes.draw do
  root 'artists#index'

    resources :artists do
      resources :songs
    end
      resources :photos, only: [:destroy]

    namespace :api do
      resources :artists do
        resources :songs
      end
        resources :photos, only: [:destroy]
    end

  end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  has_many :songs, dependent: :destroy
  validates :name, presence: true, length: { maximum: 100 }
  has_many :photos, dependent: :destroy

  def self.recently_added
    order('created_at desc')
  end

  def self.order_by_name
    order(:name)
  end
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :artist
  mount_uploader :image, ImageUploader
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :artist

  validates :name, presence: true, length: { maximum: 100 }
  validates :audio_url, length: { maximum: 255 }, allow_blank: true

  def short?
    duration < 5
  end
end

app/controllers/api/artists_controller.rb
class Api::ArtistsController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_action :set_artist, only: [:show]

  def index
    artists = Artist.all
    render status: 200, json: artists
  end

  def show
    #artist = Artist.find(params[:id])
    songs = artist.songs
    render status: 200, json: artist.songs
  end




  def set_artist
    artist = Artist.find(params[:id])
    render status: 200, json: artist
  end

  def artist_params
    params.require(:artist).permit(:name, :image_url)
  end

  def image_params
    params[:images].present? ? params.require(:images) : []
  end

end

app/controllers/api/songs_controller.rb
class Api::SongsController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_action :set_artist

  def index
    songs = Song.all
    render status: 200, json: songs
  end

  def new
    song = @artist.songs.build
  end

  # def show
  #    song = @artist.songs.find(params[:artist_id])
  #    render status: 200, json: {
  #      song: song
  #    }.to_json
  # end

  def create
    #song = Song.new(song_params)
    #song.artist = Artist.find(params[:artist_id])
    song = @artist.songs.create(song_params)

    if song.save
      render status: 201, json: {
        artist: @artist,
        song: song
      }.to_json
      #format.html {redirect_to @song.artist, notice: "Song successfully created"}
      #redirect_to @song.artist
    else
      render status: 422, json: {
        message: "Song could not be created",
        errors: song.errors
      }.to_json
      #render 'new'
    end
  end

  def destroy
    if params['id'] == 'delete_all'
      @artist.songs.destroy_all

      render status: 200, json: {
        message: "all Songs Deleted!"
      }.to_json
    else
      song = @artist.songs.find(params[:id])
      song.destroy

      render status: 200, json: {
        message: "Song Deleted!"
      }.to_json
    end



  end






  def set_artist
      @artist = Artist.find(params[:artist_id])
  end

  def song_params
    params.require(:song).permit(:name, :duration, :audio_url, :artist_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController

  def index
  	  @artists = Artist.all
  end

  def show
    @artist = Artist.find(params[:id])
    @songs = @artist.songs
    @photos = @artist.photos
  end

  def new
    @artist = @artist.new
  end

  def create
    @artist = artists.build(artist_params)

      if @artist.save
        image_params.each do |image|
          @artist.photos.create(image: image)
        end

      redirect_to edit_artist_path(@artist), notice: "Artist successfully created"
      else
        render :new
      end
  end

  def edit
    @artist = Artist.find(params[:id])
    @photos = @artist.photos
  end

  def update
    @artist = Artist.find(params[:id])
      if @artist.update(artist_params)
      image_params.each do |image|
        @artist.photos.create(image: image)
      end
      redirect_to @artist, notice: "Artist updated"
      else
      render :edit
      end
  end

  def destroy
    @artist = Artist.find(params[:id])
    @artist.destroy
    redirect_to @artist, notice: "Artist Deleted!"
  end

  private
  def artist_params
    params.require(:artist).permit(:name, :image_url)
  end

  def image_params
    params[:images].present? ? params.require(:images) : []
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def destroy
    photo = Photo.find(params[:id])
    @artist = photo.artist
    photo.destroy
      redirect_to artists_path, notice: "Photo successfully removed"
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_artist

  def index
    @songs = Song.all
    @song = Song.new
  end

  def show
     @song = @artist.songs.find(params[:artist_id])
  end

  def new
    @song = @artist.songs.new
  end

  def create
    @song = Song.new(song_params)
    @song.artist = Artist.find(params[:artist_id])
    if @song.save
      redirect_to @song.artist
    else
      render 'new'
    end
  end

  def destroy
    @song = @artist.songs.find(params[:id])
    @song.destroy
    redirect_to @artist, notice: "Song Deleted!"
  end

  def set_artist
      @artist = Artist.find(params[:artist_id])
  end

  def song_params
    params.require(:song).permit(:name, :duration, :audio_url, :artist_id)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/artists/_form.html.erb
<%= form_for @artist, html: { multipart: true } do |f| %>
<div class="form-group">
  <label>Artist's Name:</label>
  <%= f.text_field :name, placeholder: "Wtite the name of the artist", class: "form-control" %>
</div>

<label>Photos:</label>
<div class="form-group">
  <span class="button">
    Upload Photos:
    <%= file_field_tag "images[]", type: :file, multiple: true %>
  </span>
</div>

<div class="actions">
  <%= f.submit "Save", class: "button" %>
</div>

<%end%>

app/views/artists/_form_song.html.erb
<%= form_for ([@artist, @song]) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :duration %>
  <%= f.number_field :duration %>

  <%= f.label :audio_url %>
  <%= f.text_field :audio_url %>

  <%= f.submit "Create" %>
<% end %>

app/views/artists/edit.html.erb
<h1>Editing <%= @artist.name %> </h1>

<%= render 'form' %>

app/views/artists/index.html.erb
<h1 class="main-banner">Artists:</h1>

<ul>
<% @artists.each do |artist| %>
  <li>
    <h1><strong><%= link_to artist.name, artist_path(artist.id) %></strong></h1>

  <h4>Photo:</h4>
    <% artist.photos.each do |photo| %>
    <%= image_tag photo.image.thumbnail, class: "img" %>
    <p><%= link_to "Add photo", edit_artist_path(artist), class: "button" %></p>
    <p><%= link_to "Delete photo", photo_path( photo.id ), class: "button",
    method: :delete, data: { confirm: "Are you sure?" } %></p>
    <hr>
    <% end %>

  </li>
<% end %>
</ul>

app/views/artists/show.html.erb
<p>
  <h1 class="main-banner">Name of the artist:</h1>
  <h1><%= @artist.name %></h1>
  <%= link_to "Delete artist", artist_path(@artist.id), method: :delete, data: {confirm: "Are you sure?"}, class: "button" %>
</p>

<!-- LIST OF SONGS -->
<h2>List of Songs:</h2>

<% if @artist.songs.any? %>
  <ul id="songList">
    <% @artist.songs.each do |song| %>
      <li class="song_name" id="song-<%= song.id %>" ><%= song.name %></li>
      <div id="delete-song-<%= song.id %>" ><%= link_to "Delete song", url_for([@artist, song]), method: :delete, class: "button" %></div>
    <% end %>
  </ul>
<% else %>
  <p>There are no song belongs to this artist!</p>
<% end %>
<hr>

<!-- FORM -->
<div id="add-song-wrapper">
<h1> Add Song for <%= link_to @artist.name, @artist %>:</h1>

  <%= form_for ([@artist, @artist.songs.build])  do |f| %>

    <%= f.label :name %>
    <%= f.text_field :name %>
    <%= f.hidden_field :artist_id, value: @artist.id %>

    <%= f.submit "Create", data: { disable_with: false } %>
    <div><button id="delete-songs" >Delete all songs</button></div>
  <% end %>

</div>

app/views/layouts/_footer.html.erb
<footer id="page-footer">
  <p>
    Copyright &copy; 2018
    <%= link_to 'Made by Irina Ovdij', 'https://www.facebook.com/irina.ovdij' %>
  </p>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Codaisseurify</title>

    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <!-- Add jQuery -->
    <%= javascript_include_tag 'https://code.jquery.com/jquery-3.2.1.min.js' %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <br><br>
    <hr>

   <%= link_to "All Artists", root_path, class: "button_all" %>

    <%= render "layouts/footer" %>
  </body>
</html>

app/views/songs/new.html.erb
<h1>Add Song for <%= link_to @artist.name, @artist %>:</h1>

<%= form_for ([@artist, @song]) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :duration %>
  <%= f.number_field :duration %>

  <%= f.label :audio_url %>
  <%= f.text_field :audio_url %>

  <%= f.submit "Create" %>
<% end %>

app/views/songs/show.html.erb
<h1><%= @song.artist.name %></h1>

<p>Song: </p>
<%= @song.name %>